---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Carte générale

```{r admin_data}
#| fig-cap: "AP Makay (source: Bernard), carte administrative et projections de population (source: OCHA) et localités (source BNGRC)"

library(tidyverse)
library(tmap)
library(sf)
library(units)
library(methods)


makay_ap <- st_read("data/Makay_wgs84.geojson", quiet = TRUE) %>% 
  rename(Statut = SOURCETHM) %>% 
  mutate(Statut = recode(Statut, "zone tampon" = "Zone tampon"))

# Fist we dissolve the different areas
makay_union <- makay_ap %>% 
  st_union() %>% 
  st_sf() %>% 
  st_make_valid()

# Define the buffer size (in kilometers) for the square expansion
buffer_size_km <- 60

# Create a 20km buffer around Makay PA
makay_buffer <- makay_union %>%
  st_buffer(dist = set_units(buffer_size_km, km)) %>%
  st_as_sf()

# Load population estimations
pop <- read_csv("data/population/mdg_admpop_adm4_2018.csv") %>%
  select(ADM4_PCODE, pop = T_TL)

# Read administrative area boundaries
communes <- st_read(
  "data/OCHA_BNGRC admin boundaries/mdg_admbnda_adm3_BNGRC_OCHA_20181031.shp",
  quiet = TRUE) %>% 
  st_make_valid()
fokontany <- st_read(
  "data/OCHA_BNGRC admin boundaries/mdg_admbnda_adm4_BNGRC_OCHA_20181031.shp",
  quiet = TRUE) %>% 
  st_make_valid()
places <- st_read(
  "data/OCHA_BNGRC populated places/mdg_pplp_places_NGA_OCHA.shp",
  quiet = TRUE)

# Crop communes and fokontany using the square buffer
cropped_communes <- communes %>%
  filter(st_intersects(., makay_buffer, sparse = FALSE))
cropped_fokontany <- fokontany %>% 
  filter(ADM3_PCODE %in% cropped_communes$ADM3_PCODE) %>% 
  left_join(pop, by = "ADM4_PCODE") %>%
  rename(Commune = ADM3_EN, Fokontany = ADM4_EN,
         `Population 2018 (estimation)` = pop)
cropped_places <- places %>% 
  mutate(ADM3_PCODE = str_replace(COM_PCODE, "MDG", "MG"),
         FOKONTANY_DEB = str_remove(DISTRICT, "Ville I")) %>%
  filter(ADM3_PCODE %in% cropped_communes$ADM3_PCODE) %>%
  mutate(Chef_lieu = case_when(
    str_starts(FOKONTANY, PLACE_NAME) & str_starts(FOKONTANY, DISTRICT) ~ 
      "District",
    str_starts(FOKONTANY, PLACE_NAME)   & str_starts(FOKONTANY, COMMUNE) 
    ~ "Commune",
    str_starts(FOKONTANY, PLACE_NAME)  ~ "Fokontany",
    .default = ""),
    Chef_lieu = factor(Chef_lieu, levels = c("", "Fokontany", 
                                             "Commune", "District")),
    size_dot = case_when(
      Chef_lieu == "" ~ 0.001,
      Chef_lieu == "Fokontany" ~ 0.002, 
      Chef_lieu == "Commune" ~ 0.005,
      Chef_lieu == "District" ~ 0.007,
      .default = 0.001))
    

# tm_shape(makay_ap, name = "Zones de l'AP") +
#   tm_polygons(col = "Statut", alpha = 0.5) +
tmap_mode("view")
tm_shape(cropped_places, name = "Localités") +
  tm_dots(size = "size_dot", size.max = 0.05, col = "Chef_lieu",
          palette = c("lightgrey", "grey", "darkgrey", "black"),
                      id = "PLACE_NAME",
                      popup.vars = c("PLACE_NAME",
                                     "FOKONTANY",
                                     "COMMUNE")) +
  tm_shape(makay_union, name = "Périmètre exterieur de l'AP") +
  tm_borders(col = "darkgreen", lwd = 2) + 
  tm_add_legend(type = "fill", col = "darkgreen", labels = "AP Makay") +
  tm_shape(cropped_fokontany, name = "Fokontany") +
  tm_borders(col = "grey") +
  tm_fill(alpha = 0, id = "Fokontany",
          popup.vars = c("Fokontany",
                         "Population 2018 (estimation)",
                         "Commune")) +
  tm_shape(cropped_communes, name = "Communes") +
  tm_borders(col = "black")  +
  tm_basemap("OpenStreetMap") +
  tm_view(dot.size.fixed = FALSE, set.view = 9)
```


Now we create a static map:

```{r}

# Make a rayshader
library(terra)

# Step 1: Load and merge DEM files using purrr::map and reduce
dem_files <- list.files("data/nasa_srtm", full.names = TRUE)
dem_list <- dem_files %>% map(rast)
merged_dem <- reduce(dem_list, function(x, y) merge(x, y))

# Define the extent around Beronono (buffer in kilometers)
buffer_km <- c(north = 30, south = 30, east = 50, west = 50)
buffer_deg <- buffer_km / 111  # Convert km to degrees

# Create extent
beronono_extent <- ext(
  beronono_coords[1] - buffer_deg["west"],
  beronono_coords[1] + buffer_deg["east"],
  beronono_coords[2] - buffer_deg["south"],
  beronono_coords[2] + buffer_deg["north"]
)



# Crop merged DEM to the defined extent
cropped_dem <- crop(merged_dem, beronono_extent)


plot(cropped_dem)
plot(merged_dem)

# Step 2: Compute slope and aspect
slope <- terrain(cropped_dem, v = 'slope', unit = 'radians')
aspect <- terrain(cropped_dem, v = 'aspect', unit = 'radians')

# Generate the hillshade
hillshade <- shade(slope, aspect, angle = 45, direction = 315)

cropped_places2 <- cropped_places %>%
  filter(Chef_lieu %in% c("Fokontany", "Commune", "District")) %>%
  mutate(size_dot = case_when(
      Chef_lieu == "Fokontany" ~ 0.02, 
      Chef_lieu == "Commune" ~ 0.05,
      Chef_lieu == "District" ~ 0.1))

tmap_mode("plot")
# tm_shape(hillshade_raster) +
#   tm_raster(style = "cont", palette = "-Greys", legend.show = FALSE) +

tm_shape(hillshade) + 
  tm_raster(style = "cont", palette = "-Greys", legend.show = FALSE) +
tm_shape(cropped_places2) +
  tm_dots(size = "size_dot", size.max = 0.2, col = "Chef_lieu",
          palette = c("lightblue", "blue", "darkblue")) + 
  tm_legend(legend.outside = TRUE) +
  tm_shape(makay_union, name = "Périmètre exterieur de l'AP") +
  tm_borders(col = "darkgreen", lwd = 2) + 
  tm_add_legend(type = "fill", col = "darkgreen", labels = "AP Makay")

```

