# Introduction

Ce site de visualisation de données est réalisé dans le cadre du projet "Observatoire Makay-DT3Ma". Il vise à fournir des éléments de contexte aux chercheuses et chercheurs qui travaillent sur la région, à partir de données librement accessibles.[Voir le site dédié du projet Observartoire Makay-DT3Ma pour plus d'informations.](https://observamakay.hypotheses.org/)

Il s'agit notamment de nourrir l'articulation entre les bras socioéconomique, ethnoécologique et anthropologique de ce projet de recherche, en documentant à partir de sources tierces (satellitaires principalement) des évènements concrets susceptibles d'être appréhendées dans chacun des bras. On a ainsi identifié des passages de cyclones, feux de brousse/forêt et périodes de pluie/sécheresse. De par leur nature, ces évènements concrets sont circonscrits dans le temps et l'espace et documenter leur chronologie et leur localisation dans les enquêtes de chacun des bras favorisera l'étalonnage, la comparabilité et les échanges entre les bras. Concrètement, un feu de brousse de grande ampleur survenu dans une zone déterminée est susceptible d'influencer les résultats de l'enquête OR pour les localités avoisinantes (bras socioéconomique), les écosystèmes et leur perception par les populations locales (bras ethnoécologique), ou encore les représentations captées par le bras anthropologique.

Par souci de transparence et pour être en mesure de reproduire les analyses plus tard, en actualisant ou non les données sources, on travaille avec le logiciel statistique R et le système de rendus quarto. Un seul document, archivé et versionné de manière rigoureuse, contient à la fois le texte d'analyse, les traitements de données (bloc de code ci-dessous) et les visualisations de résultats. L'ensemble du code source est accessible en cliquant sur l'icône en haut à gauche de l'écran.

```{r Installation et chargement des librairies requises}
librairies_requises <- c( # On liste les librairies dont on a besoin
  "aws.s3", # Pour lire-écrire des données cloud (datalake SSP Cloud)
  "tidyverse", # toolkit for data manipulation
  "geodata", # to get municipalities
  "sf", # to handle spatial data (vectors)
  "terra", # to handle patial data (rasters)
  "mapme.biodiversity", # to compute spatial indicators
  "rstac", # necessary for mapme.biodiversity
  "tmap", # nice maps
  "zoo", # time series
  "units", # ensures units are right
  "future", # to parallelize computations
  "exactextractr", # engine for mapme.biodiversity
  "SPEI") # to compute rainfall  

# On regarde parmi ces librairies lesquelles ne sont pas installées
manquantes <- !(librairies_requises %in% installed.packages())
# On installe celles qui manquent
if(any(manquantes)) install.packages(librairies_requises[manquantes])

# Désactiver les notations scientifiques
options(scipen =999)
```

Le rendu des données est réalisé à partir de [la plateforme SSP Cloud](https://www.sspcloud.fr/) mise à disposition par l'INSEE pour le service public. 

Crédit photo: Vue du Makay © Jean-Michel Wachsberger